name: Deploy

on:
  push:
    branches: [main]

jobs:
  supabase-migrate:
    name: Supabase Migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Apply migrations
        run: supabase db push --project-ref qtokfqcirtdniejdeeby
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

  vercel-deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: supabase-migrate
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token "${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
